package com.sakthi.code.leetcode.easy1;

public class FindTheDifference {
	/*
	 * You are given two strings s and t.
	 * 
	 * String t is generated by random shuffling string s and then add one more
	 * letter at a random position.
	 * 
	 * Return the letter that was added to t.
	 * 
	 * Example 1:
	 * 
	 * Input: s = "abcd", t = "abcde" Output: "e" Explanation: 'e' is the letter
	 * that was added. Example 2:
	 * 
	 * Input: s = "", t = "y" Output: "y"
	 */
		
	public static void main(String[] args) {
		FindTheDifference obj=new FindTheDifference();
		System.out.println(obj.findTheDifference("abcd", "abcde"));
		System.out.println(obj.findTheDifference("", "y"));

	}
	
	public char findTheDifference(String s,String t) {
		int[] ch=new int[255];
		for(int i=0;i<s.length();i++) {
			ch[s.charAt(i)]++;
		}
		for(int i=0;i<t.length();i++) {
			ch[t.charAt(i)]--;
		}
		for(int i=0;i<255;i++) {
			if(ch[i]!=0) {
				return (char)i;
			}
		}
		return '\0';
	}

}
